#:schema node_modules/@deco/workers-runtime/config-schema.json
name = "deco-certifi"
scope = "deco.cx"

[deco]
workspace = "deco.cx"

[[deco.bindings]]
name = "RESEND_DECO"
type = "mcp"
integration_id = "i:ef0a00a0-8a85-4beb-845f-190e86f2f8b0"