#:schema node_modules/@deco/workers-runtime/config-schema.json
name = "deco-certify"
main = "main.ts"
compatibility_date = "2025-06-17"
compatibility_flags = [ "nodejs_compat" ]
scope = "deco.cx"

[assets]
directory = "./view-build"
binding = "ASSETS"

[deco]
workspace = "deco.cx"
enable_workflows = true
local = false

[[deco.bindings]]
name = "DATABASE"
type = "mcp"
integration_id = "i:databases-management"

[[deco.bindings]]
name = "RESEND"
type = "mcp"
integration_id = "i:ef0a00a0-8a85-4beb-845f-190e86f2f8b0"

[[migrations]]
tag = "v1"
new_classes = [ "Workflow" ]

[durable_objects]
[[durable_objects.bindings]]
name = "DECO_CHAT_WORKFLOW_DO"
class_name = "Workflow"

[[rules]]
type = "Text"
globs = [ "**/*.sql" ]
fallthrough = true